# NumPy 简单使用

In [5]:
import numpy as np

a = np.zeros((3, 2))
type(a)

print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


numpy.ndarray

In [13]:
a.shape

(3, 5)

In [14]:
a.dtype

dtype('float64')

In [15]:
a = np.zeros((4, 2), dtype=np.int32)
a.dtype

dtype('int32')

In [9]:
np.ones((3, 5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(2, 4)

array([[0.46107565, 0.38526164, 0.10880539, 0.41913105],
       [0.79462788, 0.09105456, 0.99150937, 0.41531401]])

In [16]:
b = a.astype(int)
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

print(a / b)

[5 7 9]
[0.25 0.4  0.5 ]


In [21]:
np.dot(a, b) # 点乘

32

In [26]:
# 矩阵乘法 np.matmul()
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a @ b

array([[19, 22],
       [43, 50]])

In [28]:
a = np.array([1, 2, 3])
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [29]:
print(np.sin(a))
print(np.cos(a))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [31]:
print(np.log(a))
print(np.power(a, 2))

[0.         0.69314718 1.09861229]
[1 4 9]


In [32]:
a * 5 # 广播 （Broadcasting）

array([ 5, 10, 15])

In [34]:
a = np.array([[1],
             [10],
             [20]])
b = np.array([1, 2, 3])

a + b

array([[ 2,  3,  4],
       [11, 12, 13],
       [21, 22, 23]])

In [35]:
a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())

1
5


In [36]:
print(a.argmin())
print(a.argmax())

0
4


In [37]:
a.sum()

15

In [39]:
np.mean(a) # 平均值

3.0

In [41]:
np.median(a) # 中位数

3.0

In [42]:
a.var() # 方差

2.0

In [43]:
a.std() # 标准方差

1.4142135623730951

In [44]:
a = np.array([[1, 2, 3, 4, 5], 
              [5, 6, 7, 8, 9]])
a.sum(axis=0) # 按列求和

array([ 6,  8, 10, 12, 14])

In [45]:
a.sum(axis=1) # 按行求和

array([15, 35])

In [46]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a[0, 1]

2

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[a < 3]

array([0, 1, 2])

In [49]:
a[(a > 3) & (a % 2 == 0)]

array([4, 6, 8])

In [51]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a[0, 0:2]

array([1, 2])

In [52]:
a[0, :]

array([1, 2, 3])

In [53]:
a[0]

array([1, 2, 3])

In [55]:
a = np.arange(10)
a[0:9:2]

array([0, 2, 4, 6, 8])

In [56]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])