In [2]:
import numpy as np

In [3]:
funs = dir(np)
i = 0
for fun in funs:
    print(fun, end=" ")
    i += 1
    if i % 5 == 0:
        print()


ALLOW_THREADS AxisError BUFSIZE CLIP ComplexWarning 
DataSource ERR_CALL ERR_DEFAULT ERR_IGNORE ERR_LOG 
ERR_PRINT ERR_RAISE ERR_WARN FLOATING_POINT_SUPPORT FPE_DIVIDEBYZERO 
FPE_INVALID FPE_OVERFLOW FPE_UNDERFLOW False_ Inf 
Infinity MAXDIMS MAY_SHARE_BOUNDS MAY_SHARE_EXACT ModuleDeprecationWarning 
NAN NINF NZERO NaN PINF 
PZERO RAISE RankWarning SHIFT_DIVIDEBYZERO SHIFT_INVALID 
SHIFT_OVERFLOW SHIFT_UNDERFLOW ScalarType Tester TooHardError 
True_ UFUNC_BUFSIZE_DEFAULT UFUNC_PYVALS_NAME VisibleDeprecationWarning WRAP 
_CopyMode _NoValue _UFUNC_API __NUMPY_SETUP__ __all__ 
__builtins__ __cached__ __config__ __deprecated_attrs__ __dir__ 
__doc__ __expired_functions__ __file__ __getattr__ __git_version__ 
__loader__ __name__ __package__ __path__ __spec__ 
__version__ _add_newdoc_ufunc _distributor_init _financial_names _globals 
_mat _pyinstaller_hooks_dir _pytesttester _version abs 
absolute add add_docstring add_newdoc add_newdoc_ufunc 
all allclose alltrue amax amin 
angle any append

# 1 创建数组

## 1.1 使用Python序列创建数组

In [4]:
lst_a  = [1, 2, 3]
arr1 = np.array(lst_a)
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
dic_a = {
    "name" : "kobayashi",
    "age" : 19,
}

arr2 = np.array(dic_a)
print(arr2)
print(type(arr2))

{'name': 'kobayashi', 'age': 19}
<class 'numpy.ndarray'>


## 2 NumPy 自动生成数组

1. arange 创建顺序数组
2. zeros 创建元素全为 0 的数组
3. ones 创建元素全为 1 的数组
4. eye 创建对角数组
5. random 随机生成数组
6. linspace 生成均匀间隔数组

In [6]:
# arange 函数
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# zeros 函数
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# ones 函数
arr5 = np.ones((2, 3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# eye 函数
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# random 函数

# 从 [0, 1) 中随机取值
arr7 = np.random.rand(2, 3)
print(arr7)

# 创建指定区间的随机整数数组
arr8 = np.random.randint(1, 10, (2, 3))
print(arr8)

# 创建指定区间的随机浮点数数组
arr9 = np.random.uniform(1, 10, (2, 3))
print(arr9)

[[0.94922109 0.0115545  0.07435771]
 [0.32311869 0.87988144 0.84836357]]
[[6 1 1]
 [4 6 9]]
[[6.55078792 5.25637708 1.10558717]
 [5.6974706  2.60169316 2.94824553]]


In [11]:
# linspace 函数

# 均匀比例的数组
arr10 = np.linspace(-1, 1, 20)
arr10

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [12]:
# empty 函数
arr11 = np.empty((2, 3))
arr11

array([[6.55078792, 5.25637708, 1.10558717],
       [5.6974706 , 2.60169316, 2.94824553]])

# 2 操作数组的形状和维度

## 1 查看数组的维度与形状

1. 维度个数 ndim
2. 维度大小 shape
3. 打乱数组 random.shuffle

In [13]:
arr = np.arange(20)
np.random.shuffle(arr)
arr

array([ 4,  2,  9, 10, 11,  5,  8,  7, 14,  1,  3, 16, 17, 15, 12, 19,  0,
       13, 18,  6])

## 2 修改数组的维度与形状

1. 修改数组的维度 reshape
2. 翻转数组 transpose | T
3. 展开为一位数组 flatten() | ravel() | reshape()

In [14]:
arr.ndim

1

In [15]:
arr2 = arr.reshape(4, 5)
arr2

array([[ 4,  2,  9, 10, 11],
       [ 5,  8,  7, 14,  1],
       [ 3, 16, 17, 15, 12],
       [19,  0, 13, 18,  6]])

In [16]:
arr2.transpose()

array([[ 4,  5,  3, 19],
       [ 2,  8, 16,  0],
       [ 9,  7, 17, 13],
       [10, 14, 15, 18],
       [11,  1, 12,  6]])

In [17]:
arr2.flatten()

array([ 4,  2,  9, 10, 11,  5,  8,  7, 14,  1,  3, 16, 17, 15, 12, 19,  0,
       13, 18,  6])

In [18]:
arr2.reshape(1, 20)

array([[ 4,  2,  9, 10, 11,  5,  8,  7, 14,  1,  3, 16, 17, 15, 12, 19,
         0, 13, 18,  6]])

# 3 数组的拼接与分割

## 1 数组拼接

1. 横向拼接 hstack
2. 纵向拼接 vstack

In [19]:
# 横向拼接
arr3 = np.arange(20).reshape(4, 5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
np.hstack((arr2, arr3))

array([[ 4,  2,  9, 10, 11,  0,  1,  2,  3,  4],
       [ 5,  8,  7, 14,  1,  5,  6,  7,  8,  9],
       [ 3, 16, 17, 15, 12, 10, 11, 12, 13, 14],
       [19,  0, 13, 18,  6, 15, 16, 17, 18, 19]])

In [21]:
np.vstack((arr2, arr3))

array([[ 4,  2,  9, 10, 11],
       [ 5,  8,  7, 14,  1],
       [ 3, 16, 17, 15, 12],
       [19,  0, 13, 18,  6],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# 水平分割
np.hsplit(arr3, 5)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [23]:
np.vsplit(arr2, 2)

[array([[ 4,  2,  9, 10, 11],
        [ 5,  8,  7, 14,  1]]),
 array([[ 3, 16, 17, 15, 12],
        [19,  0, 13, 18,  6]])]

In [25]:
np.array_split(arr2, 3, axis=0)

[array([[ 4,  2,  9, 10, 11],
        [ 5,  8,  7, 14,  1]]),
 array([[ 3, 16, 17, 15, 12]]),
 array([[19,  0, 13, 18,  6]])]

In [26]:
np.array_split(arr2, 3, axis=1)

[array([[ 4,  2],
        [ 5,  8],
        [ 3, 16],
        [19,  0]]),
 array([[ 9, 10],
        [ 7, 14],
        [17, 15],
        [13, 18]]),
 array([[11],
        [ 1],
        [12],
        [ 6]])]

# 4 切片与索引

In [27]:
arr

array([ 4,  2,  9, 10, 11,  5,  8,  7, 14,  1,  3, 16, 17, 15, 12, 19,  0,
       13, 18,  6])

In [28]:
arr[0:6]

array([ 4,  2,  9, 10, 11,  5])

In [29]:
arr[::-1]

array([ 6, 18, 13,  0, 19, 12, 15, 17, 16,  3,  1, 14,  7,  8,  5, 11, 10,
        9,  2,  4])

## 布尔索引

In [30]:
arr > 5

array([False, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [32]:
arr[arr > 5]

array([ 9, 10, 11,  8,  7, 14, 16, 17, 15, 12, 19, 13, 18,  6])

In [33]:
arr2

array([[ 4,  2,  9, 10, 11],
       [ 5,  8,  7, 14,  1],
       [ 3, 16, 17, 15, 12],
       [19,  0, 13, 18,  6]])

In [36]:
arr2[1:, 2:]

array([[ 7, 14,  1],
       [17, 15, 12],
       [13, 18,  6]])

In [44]:
arr2[0:2, 2 : 4]

array([[ 9, 10],
       [ 7, 14]])

In [45]:
arr2[arr2 > 5]

array([ 9, 10, 11,  8,  7, 14, 16, 17, 15, 12, 19, 13, 18,  6])

# 5 数据的增删改

1. 增：增加数据实际上就是将不同的数进行拼接
2. 改：修改实际上就是对元素进行索引，然后重新赋值
3. 删：
   - 切片
   - delete

In [50]:
arr = np.random.randint(0, 10, (4,5))
arr

array([[5, 3, 6, 3, 6],
       [0, 0, 2, 1, 3],
       [4, 9, 0, 6, 9],
       [4, 3, 9, 3, 4]])

In [55]:
arr[:3, :3] = [[11, 11, 11], [11, 11, 11], [11, 11, 11]]
arr

array([[11, 11, 11,  3,  6],
       [11, 11, 11,  1,  3],
       [11, 11, 11,  6,  9],
       [ 4,  3,  9,  3,  4]])

In [59]:
np.delete(arr, arr[3])

array([11, 11, 11, 11, 11, 11,  1, 11, 11, 11,  6,  9,  4,  3,  9,  3,  4])

# 6 NumPy 中常用函数

**统计函数**

函数|说明
-|-
sum | 计算数组中的和
mean | 计算数组中的均值
var | 计算数组中的方差
std | 计算数组中的标准差
max | 计算数组中的最大值
min | 计算数组中的最小值
argmax | 返回数组中的最大元素的索引
argmin | 返回数组中的最小元素的索引
cumsun | 计算数组中所有元素的累计值
cumprod | 计算数组中所有元素的累计积

字符串函数

函数 | 描述
-|-
add() | 对两个数组的逐个字符串元素进行连接
multiply() | 返回按元素多重连接后的字符串
center() | 居中字符串
capitalize() | 将字符串的第一个字母转换为大写
title() | 将字符串中的每个单词的第一个字母转换为大写
lower() | 数组元素转换为小写
upper() | 数组元素转换为大写
split() | 指定分隔符对字符串进行分割，并返回数组列表
splitlines() | 返回元素中的行列表，以换行符分割
strip() | 移除元素开头或者结尾处的特定字符
join() | 通过指定分隔符来连接数组中的元素
replace() | 使用新字符串替换字符串中的所有子字符串
decode() | 数组元素依次调用 str.decode()
encode() | 数组元素依次调用 str.encode()

In [60]:
a = np.array(["data", "science", "is", "fun"])
a

array(['data', 'science', 'is', 'fun'], dtype='<U7')

In [61]:
np.char.upper(a)

array(['DATA', 'SCIENCE', 'IS', 'FUN'], dtype='<U7')

算数函数

函数名称 | 函数说明
-|-
ceil() | 向上最接近的整数，参数是 numebr 或 array
floor()  | 向下最接近的整数，参数是 numebr 或 array
rint() | 四舍五入，参数是 number 或 array
isnan() | 判断元素是否为 NaN，参数是 number 或 array
multiply() | 元素相乘，参数是 number 或 array
divide() | 元素相除，参数是 number 或 array
abs() | 元素的绝对值，参数是 number 或 array
where(condition, x, y) | 三元运算符, x if condition else y 