In [1]:
# 导入numpy库，并且重命名为np
import numpy as np

In [20]:
# 打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    fou

In [21]:
# 创建一个长度为10的空向量
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 找到任何一个数组的内存大小
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [23]:
# 如何得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [24]:
# 创建一个长度为10并且除了第五个值为1的空向量
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [25]:
# 创建一个值域范围从10到49的向量
data = np.arange(10, 50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
# 创建一个值域范围从10到49的向量，并将其反转
data = np.arange(50)
data = data[::-1]
data

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [27]:
# 创建一个 3x3 并且值从0到8的矩阵
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

In [29]:
# 创建一个 3x3 的单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# 创建一个 3x3x3的随机数组
a = np.random.random((3, 3, 3))
a

array([[[0.71208466, 0.67729205, 0.43108067],
        [0.89171806, 0.96928836, 0.21730028],
        [0.21063764, 0.67487711, 0.91368627]],

       [[0.39853787, 0.62455682, 0.28342094],
        [0.27802804, 0.44767764, 0.21966923],
        [0.43248576, 0.18586793, 0.74578855]],

       [[0.33872828, 0.6693363 , 0.7830342 ],
        [0.70600541, 0.75576677, 0.45216737],
        [0.41394525, 0.54526658, 0.23018764]]])

In [31]:
# 创建一个 10x10 的随机数组并找到它的最大值和最小值
a = np.random.random((10, 10))
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.013248686597259973 0.9988270330922665


In [32]:
# 创建一个长度为30的随机向量并找到它的平均值
a = np.random.random(30)
a_mean = a.mean()
print(a_mean)

0.5270193919080657


In [33]:
# 创建一个二维数组，其中边界值为1，其余值为0
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
# 对于一个存在数组，如何添加一个用0填充的边界?
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# 以下表达式运行的结果分别是什么?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [36]:
# 创建一个 5x5 的矩阵，并设置值1,2,3,4落在其对角线下方位置
data = np.diag(1 + np.arange(4), k=-1)
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [37]:
# 创建一个 8x8 的矩阵，并且设置成棋盘样式
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [38]:
# 考虑一个（6，7，8）形状的数组，其第100个元素的索引（x，y，z）是什么?
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [39]:
# 用tile函数去创建一个 8x8 的棋盘样式矩阵
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [40]:
# 对一个5x5的随机矩阵做标准化
a = np.random.random((5, 5))
a = (a - np.mean(a)) / (np.std(a))
a

array([[ 1.2399857 , -1.67034037, -0.8089409 ,  1.52255443, -0.51342727],
       [-0.89546122, -0.30008416,  1.57411612, -0.39881082,  0.46230025],
       [ 0.37127009, -0.05888112,  1.60152319,  0.24835243,  0.26906873],
       [ 1.1491399 , -1.33421   ,  1.65460968,  0.06974563, -1.58497385],
       [-1.25654133, -0.27261633,  0.17030462, -0.77537196, -0.46331144]])

In [41]:
# 创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype
color = np.dtype([  ("r", np.ubyte, 1),
                    ("g", np.ubyte, 1),
                    ("b", np.ubyte, 1),
                    ("a", np.ubyte, 1)  ])
color

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_20860\373753137.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([  ("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [42]:
# 一个5x3的矩阵和一个3x2的矩阵相乘，实矩阵的积是什么?

# a = np.dot(np.ones((5, 3)), np.ones((3, 2)))
# a

a = np.ones((5, 3)) @ np.ones((3, 2))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [43]:
# 给定一个一维数组，对其在3到8之间的所有元素取反
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [44]:
# 下面脚本运行后的结果是什么?
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [45]:
# 考虑一个整数向量Z，下列表达合法的是哪个?
Z = np.arange(5, dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)    
# Z<Z>Z

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [46]:
# 下列表达式的结果分别是什么?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_20860\3387418362.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_20860\3387418362.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [47]:
# 如何从零位对浮点数组做舍入 ?
a = np.random.uniform(-10,+10,10)
print(a)
print (np.copysign(np.ceil(np.abs(a)), a))

[-9.12248055  5.40183825  7.39546862 -8.51914555  0.11994267 -1.29341868
  9.54061626 -5.92553176 -9.12480968 -0.6001196 ]
[-10.   6.   8.  -9.   1.  -2.  10.  -6. -10.  -1.]


In [48]:
# 如何找到两个数组中的共同元素?
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[2 3 5 8]


In [49]:
# 如何忽略所有的 numpy 警告（尽管不建议这么做）?
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [50]:
np.seterr(**defaults)
Z = np.ones(1) / 0

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_20860\3746067005.py:2: RuntimeWarning: divide by zero encountered in true_divide
  Z = np.ones(1) / 0


In [51]:
# 下面的表达式是正确的吗?
#   nan            1j
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_20860\2721689056.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [52]:
# 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"yesterday: {yesterday} today: {today} tomorrow: {tomorrow}")

yesterday: 2022-12-22 today: 2022-12-23 tomorrow: 2022-12-24


In [53]:
# 如何得到所有与2016年7月对应的日期？
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [54]:
# 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [55]:
# 用五种不同的方法去提取一个随机数组的整数部分
a = np.random.uniform(0, 10, 10)
print(a - a%1)

[7. 3. 1. 9. 5. 7. 5. 1. 6. 8.]


In [56]:
# 创建一个5x5的矩阵，其中每行的数值范围从0到4
a = np.zeros((5, 5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [57]:
# 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), dtype=float, count=-1) # a = np.fromiter((x for x in range(10)), dtype=float, count=-1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
# 创建一个长度为10的随机向量，其值域范围从0到1，但不包括0和1
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [59]:
# 创建一个长度为10的随机向量，并将其排序
a = np.random.randint(0, 10, 10)
a.sort()
a

array([0, 3, 5, 5, 6, 6, 6, 7, 8, 9])

In [60]:
# 对于一个小数组，如何用比 np.sum更快的方式对其求和？
a = np.arange(10)
np.add.reduce(a)

45

In [61]:
# 对于两个随机数组A和B，检查它们是否相等
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
np.allclose(a, b)


False

In [62]:
# 创建一个只读数组(read-only)
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [ ]:
# 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.78991835 0.47107172 0.6532637  0.88302193 0.66694681 0.78696029
 1.17305675 0.2819286  0.56842421 0.76234967]
[0.70750139 0.67671178 0.8882485  1.46483816 1.39379161 1.46829534
 0.76148733 0.2450285  0.96245817 1.19602676]


In [ ]:
# 创建一个长度为10的向量，并将向量中的最大值替换为1
a = np.random.random(10)
a[a.argmax()] = 1
a

array([0.29868558, 0.45175298, 1.        , 0.83120173, 0.49848077,
       0.85561521, 0.68187866, 0.7321764 , 0.84006973, 0.7615155 ])

In [ ]:
# 创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域
a = np.zeros((5,5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
# 给定两个数组X和Y，构造Cauchy矩阵C（Cij =1/(xi - yj)）
X = np.arange(8)
Y = X + 0.5
# C = 1.0 / np.subtract.outer(X, Y)
C = 1.0 / (X[:,None] - Y)
np.linalg.det(C)

3638.1636371179666

In [ ]:
# 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [ ]:
# 如何打印一个数组中的所有数值?
import sys
np.set_printoptions(threshold=sys.maxsize)
a = np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 给定标量时，如何找到数组中最接近标量的值？
a = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(a-v)).argmin()
a[index]

49

In [ ]:
# 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
a = np.zeros(10, [('position', [ ('x', float, 1), ('y', float, 1)]), ('color', [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
a

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_6608\2656576320.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [('position', [ ('x', float, 1), ('y', float, 1)]), ('color', [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [ ]:
# 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
a = np.random.random((10, 2))
x, y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.36447127, 0.62373884, 0.18516713, 0.44855925,
        0.35188442, 0.3998194 , 0.59424892, 0.13633978, 0.10924879],
       [0.36447127, 0.        , 0.7989032 , 0.52570855, 0.7134757 ,
        0.47218706, 0.18594624, 0.93115878, 0.35016379, 0.45287496],
       [0.62373884, 0.7989032 , 0.        , 0.71178776, 0.98516229,
        0.32704939, 0.66186215, 0.48432968, 0.51273986, 0.53717025],
       [0.18516713, 0.52570855, 0.71178776, 0.        , 0.28481522,
        0.49783582, 0.58365976, 0.54052967, 0.30512958, 0.19217941],
       [0.44855925, 0.7134757 , 0.98516229, 0.28481522, 0.        ,
        0.78203337, 0.81961962, 0.71931534, 0.58108099, 0.47692652],
       [0.35188442, 0.47218706, 0.32704939, 0.49783582, 0.78203337,
        0.        , 0.34843797, 0.57287613, 0.21845273, 0.30601866],
       [0.3998194 , 0.18594624, 0.66186215, 0.58365976, 0.81961962,
        0.34843797, 0.        , 0.88222686, 0.31937476, 0.4515651 ],
       [0.59424892, 0.93115878, 0.4843296

In [ ]:
# 如何将32位的浮点数(float)转换为对应的整数(integer)
a = np.arange(10, dtype=np.int32)
a = a.astype(np.float32, copy=False)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
# 如何读取以下文件?
# 1,2,3,4,5
from io import StringIO
# 使用 StringIO 在内存中创建文件对象
text = StringIO("1, 2, 3, 4, 5") 
# 使用 genfromtxt 读取文件
np.genfromtxt(text, delimiter=",")

array([1., 2., 3., 4., 5.])

In [ ]:
# 对于numpy数组，enumerate的等价操作是什么？
a = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(a):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# 生成一个通用的二维Gaussian-like数组
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
g


array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

In [70]:
# 对一个二维数组，如何在其内部随机放置p个元素?
n = 10
p = 3

a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
print(a)

b = np.zeros((n,n))
for i in range(p):
    b[np.random.randint(n)][np.random.randint(n)] = 1
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
# 减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)

# 方法1
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

# 方法2
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.17894826  0.12637703 -0.10317538 -0.18667706  0.08259109  0.07904218
  -0.22338647  0.2581512  -0.00588136 -0.20598949]
 [ 0.06446184  0.44131349 -0.05897822  0.38654046 -0.46392687  0.17958873
  -0.1652749   0.13255597 -0.43226607 -0.08401441]
 [ 0.01805756 -0.40839249 -0.23787504  0.18974352  0.28523921  0.13820335
  -0.28969398 -0.35268756  0.27567397  0.38173146]
 [-0.07143428 -0.43240128  0.49227749  0.0434156   0.43095966 -0.3914179
  -0.06821212  0.19403493 -0.05230577 -0.14491633]
 [-0.1073869   0.51335919 -0.1346867   0.33403662 -0.30198136 -0.20242003
   0.49108078 -0.01391456 -0.22018865 -0.35789839]]
[[ 0.17894826  0.12637703 -0.10317538 -0.18667706  0.08259109  0.07904218
  -0.22338647  0.2581512  -0.00588136 -0.20598949]
 [ 0.06446184  0.44131349 -0.05897822  0.38654046 -0.46392687  0.17958873
  -0.1652749   0.13255597 -0.43226607 -0.08401441]
 [ 0.01805756 -0.40839249 -0.23787504  0.18974352  0.28523921  0.13820335
  -0.28969398 -0.35268756  0.27567397  0.38173146]


In [82]:
# 如何通过对第n列对一个数组进行排序？
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[2 9 6]
 [5 8 5]
 [2 0 4]]
[[2 0 4]
 [5 8 5]
 [2 9 6]]


In [85]:
# 如何检查一个二维数组是否有空列？
a = np.random.randint(0, 3, (3,10))
print((~a.any(axis=0)).any())

False


In [5]:
# 从数组中的给定值中找出最近的值
a = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(a-v)).argmin()
a[index]


54

In [2]:
# 如何使用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]
