In [1]:
import numpy as np

In [17]:
# 1
arr1 = np.zeros((8, 8))
arr2 = np.ones((1, 8))
arr3 = np.ones((10, 1))

arr4 = np.hstack((arr3, np.vstack((arr2, arr1, arr2)), arr3))
arr4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
# 2
arr = np.eye(4)
for i in range(4):
    arr[i, i] += i
arr

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [153]:
# 3
arr = np.random.rand(5, 5)
print(arr)
max = np.max(arr)
min = np.min(arr)
# 将矩阵中的最大值和最小值分别替换为 1 与 0，并将其它的元素映射到 1 与 0 之间
arr = (arr - min) / (max - min)
print(arr)


[[0.99824813 0.86714302 0.30054942 0.09988081 0.73115682]
 [0.3239248  0.69111951 0.75697147 0.06802548 0.00968747]
 [0.32446622 0.00407001 0.90218853 0.14912875 0.47606975]
 [0.26962831 0.09337164 0.38313282 0.38903983 0.22373471]
 [0.6900253  0.70387794 0.53332717 0.82630043 0.72778597]]
[[1.         0.86812714 0.29821558 0.09637187 0.73134461]
 [0.32172785 0.69107284 0.75731042 0.06432999 0.00565036]
 [0.32227244 0.         0.90337788 0.1459082  0.47476376]
 [0.26711341 0.08982458 0.38128259 0.38722419 0.22095105]
 [0.68997222 0.70390599 0.53235647 0.82704537 0.72795402]]


In [55]:
# 4
arr = np.random.rand(30)
print(arr)
arr.mean()

[0.5408544  0.7980945  0.60562288 0.49243132 0.3467506  0.7392843
 0.90704542 0.48833987 0.47753942 0.84973248 0.39113586 0.05905265
 0.12761505 0.20804998 0.52182462 0.53537188 0.49118892 0.91518119
 0.61821405 0.80320839 0.89603739 0.39692546 0.14768898 0.54529064
 0.14812682 0.35078605 0.24068635 0.94873678 0.59701774 0.71537391]


0.5301069307283997

In [58]:
# 5
arr = (np.zeros(10))
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [60]:
# 6
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [61]:
# 7
arr1 = np.zeros((5, 5))
arr2 = np.arange(0, 5)
arr2 + arr1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [65]:
# 8
arr = np.linspace(0, 1, 12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [73]:
# 9
arr = np.random.randint(-100, 100, 10)
arr.sort()
arr

array([-87, -62, -58, -11,  -2,   1,  37,  39,  54,  61])

In [75]:
# 10
arr = np.random.randint(-100, 100, 10)
print(arr)
arr[np.argmax(arr)] = 0
arr

[ 74 -96 -46 -81   1 -97   1 -87  -1 -72]


array([  0, -96, -46, -81,   1, -97,   1, -87,  -1, -72])

In [77]:
# 11
arr = np.random.randint(-100, 100, (5, 5))
print(arr)
arr[2].sort()
arr

[[-53 -51 -97  42  25]
 [ 75 -29  82 -70 -24]
 [-25 -30  52  23 -15]
 [ 44  17 -30  49  13]
 [-51 -19  63   3 -99]]


array([[-53, -51, -97,  42,  25],
       [ 75, -29,  82, -70, -24],
       [-30, -25, -15,  23,  52],
       [ 44,  17, -30,  49,  13],
       [-51, -19,  63,   3, -99]])

In [84]:
# 12
# 给定一个四维矩阵，得到最后两维的和
arr = np.random.randint(-100, 100, (2, 2, 2, 2))
print(arr)
arr.sum(axis=(-2, -1))

[[[[ 68 -48]
   [ 33   4]]

  [[ 27  51]
   [-27  69]]]


 [[[ 60  48]
   [ 98 -42]]

  [[ 59 -69]
   [-20  43]]]]


array([[ 57, 120],
       [164,  13]])

In [91]:
# 13_1
arr1 = np.random.randint(-10000, 10000, 100000)
arr1**3

array([  974437693, -1833016521, -2088296952, ...,  1413548104,
       -1963708224, -2117120731], dtype=int32)

In [92]:
# 13_2
import random
arr2 = np.array([random.randint(-10000, 10000) for i in range(100000)])
arr2**3 

array([ 1784693272, -1479340705,  -190825905, ..., -1217255129,
        1726480745,   -14437875], dtype=int32)

In [113]:
# 14
arr = np.random.randint(-10, 10, (5, 5))
arr = arr.astype(float)
print(arr)
for i in range(arr.shape[0]):
    arr[i] -= arr[i].mean()
arr

[[  4.   9.  -6.  -2.   2.]
 [ -5.  -5.   5.  -2.   3.]
 [ -7.   9.   1.   4.  -1.]
 [  8.   1.   7.  -6.  -4.]
 [-10.   3. -10.   1.  -1.]]


array([[ 2.6,  7.6, -7.4, -3.4,  0.6],
       [-4.2, -4.2,  5.8, -1.2,  3.8],
       [-8.2,  7.8, -0.2,  2.8, -2.2],
       [ 6.8, -0.2,  5.8, -7.2, -5.2],
       [-6.6,  6.4, -6.6,  4.4,  2.4]])

In [115]:
# 15 正则化一个矩阵
arr = np.random.randint(-10, 10, (5, 5))
(arr - np.min(arr))/(arr.max() - arr.min())

array([[0.66666667, 0.        , 0.05555556, 0.55555556, 0.83333333],
       [0.22222222, 0.55555556, 0.33333333, 0.77777778, 0.16666667],
       [0.5       , 0.11111111, 0.05555556, 0.94444444, 0.72222222],
       [0.5       , 1.        , 1.        , 0.72222222, 0.94444444],
       [0.77777778, 0.66666667, 0.16666667, 0.72222222, 0.05555556]])

In [120]:
# 16
arr1 = np.random.randint(-10, 10, (5, 3))
arr2 = np.random.randint(-10, 10, (3, 2))
print(arr1, arr2)
arr1 @ arr2

[[-10   7  -9]
 [  4  -4  -7]
 [  3  -1  -2]
 [ -6   8  -9]
 [  4  -6   8]] 
 [[ 8 -3]
 [ 4  7]
 [ 6  1]]


array([[-106,   70],
       [ -26,  -47],
       [   8,  -18],
       [ -70,   65],
       [  56,  -46]])

In [125]:
# 17
arr = np.random.randint(-10, 10, (5, 5))
print(arr)
# 交换第一行与第二行
arr[[0, 1]] = arr[[1, 0]]
arr

[[-2  1  2 -5  3]
 [ 6  7  5  1  0]
 [ 3  7  4 -4  4]
 [ 0 -5  2 -1  3]
 [-8  2  1 -4 -3]]


array([[ 6,  7,  5,  1,  0],
       [-2,  1,  2, -5,  3],
       [ 3,  7,  4, -4,  4],
       [ 0, -5,  2, -1,  3],
       [-8,  2,  1, -4, -3]])

In [138]:
# 18
arr = np.array([1, 2, 3, 4, 5])
# 每个元素之间插入三个0

arr = np.insert(arr, np.arange(1, arr.size), 0)
print(arr)
np.insert(arr, np.arange(1, arr.size), 0)

[1 0 2 0 3 0 4 0 5]


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [152]:
# 19
arr = np.zeros((8, 8))
# 变为 0 1 交替的矩阵
arr[1::2, ::2] = 1
# print(arr)
arr[::2, 1::2] = 1
arr


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])